# Generated by Django 5.1.5 on 2025-02-02 05:35

import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.FilePathField(
                        path=pathlib.PurePosixPath("/Volumes/media"), unique=True
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        help_text="Device that the file is from, according to the host OS.",
                        max_length=20,
                    ),
                ),
                (
                    "inode_number",
                    models.CharField(
                        help_text="An OS-dependent unique identifier for file within the context of the recorded device. On Unix-like systems, this is the inode number. On Windows, this is the file index.",
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.PositiveBigIntegerField(
                        help_text="Size of the file (in bytes)."
                    ),
                ),
                (
                    "hash",
                    models.BinaryField(
                        blank=True,
                        help_text="XXH128 hash of the file contents.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "default_related_name": "files",
                "indexes": [
                    models.Index(fields=["path"], name="media_file_path_4bde6e_idx"),
                    models.Index(
                        fields=["device", "inode_number"],
                        name="media_file_device_5caea3_idx",
                    ),
                ],
            },
        ),
    ]
